version: '3.3'

services:
  mysql-service:
    image: mysql:latest
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: crmall
      MYSQL_PASSWORD: crmal@123
      MYSQL_DATABASE: crmall
    volumes:
      - ./.docker/db:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql-service
